'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import LogoutButton from '@/components/LogoutButton';
import api from '@/lib/api';

interface Test {
    _id: string;
    title: string;
    description: string;
    field: string;
    testLevel: string;
    instructions: string;
    createdAt: string;
}

export default function AdminAssignments() {
    const [tests, setTests] = useState<Test[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadTests();
    }, []);

    const loadTests = async () => {
        try {
            const { data } = await api.get('/tests');
            setTests(data);
        } catch (error) {
            console.error('Error loading tests:', error);
        } finally {
            setLoading(false);
        }
    };

    const getBadgeColor = (level: string) => {
        switch (level) {
            case 'HIGH': return 'bg-purple-500';
            case 'MEDIUM': return 'bg-blue-500';
            case 'LOW': return 'bg-green-500';
            default: return 'bg-gray-500';
        }
    };

    if (loading) {
        return <div className="container mx-auto py-8">Loading...</div>;
    }

    return (
        <div className="container mx-auto py-8">
            <div className="mb-8 flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold mb-2">Test Assignments</h1>
                    <p className="text-muted-foreground">
                        View all skill tests generated by Gemini AI
                    </p>
                </div>
                <LogoutButton />
            </div>

            {tests.length === 0 ? (
                <Card>
                    <CardContent className="py-12 text-center">
                        <p className="text-muted-foreground">No tests available</p>
                    </CardContent>
                </Card>
            ) : (
                <div className="grid gap-6">
                    {tests.map((test) => (
                        <Card key={test._id}>
                            <CardHeader>
                                <div className="flex justify-between items-start">
                                    <div className="flex-1">
                                        <CardTitle className="text-2xl mb-2">{test.title}</CardTitle>
                                        <div className="flex gap-2 items-center">
                                            <Badge className={`${getBadgeColor(test.testLevel)} text-white`}>
                                                {test.testLevel} Level
                                            </Badge>
                                            <Badge variant="outline">{test.field}</Badge>
                                        </div>
                                    </div>
                                </div>
                            </CardHeader>
                            <CardContent>
                                <div className="space-y-4">
                                    <div>
                                        <h3 className="font-semibold mb-2">Description:</h3>
                                        <p className="text-muted-foreground">{test.description}</p>
                                    </div>

                                    <div>
                                        <h3 className="font-semibold mb-2">Instructions:</h3>
                                        <div
                                            className="prose prose-sm max-w-none text-muted-foreground"
                                            dangerouslySetInnerHTML={{
                                                __html: test.instructions.replace(/\n/g, '<br/>')
                                            }}
                                        />
                                    </div>

                                    <div className="text-sm text-muted-foreground">
                                        <p>Created: {new Date(test.createdAt).toLocaleDateString()}</p>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            )}
        </div>
    );
}
